import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import Backend from "~/constants/backend-routes";
import type { AppDispatch, RootState } from "~/redux/store";
import Ajax from "~/utils/ajax";
import type { EntryFolders, EntrySearchParams } from "./entry-schemas";
import { entryFoldersSchema, entryItemsSchema } from "./entry-schemas";

type EntryState = {
    status: "idle" | "loading" | "succeeded" | "failed";
    items: EntryFolders;
    filter: EntrySearchParams;
    hideFilters: boolean;
    hideList: boolean;
};

const initialState: EntryState = {
    status: "idle",
    items: [],
    filter: {},
    hideFilters: false,
    hideList: false,
};

export const listFolder = createAsyncThunk<
    EntryState,
    void,
    {
        dispatch: AppDispatch;
        state: RootState;
    }
>(
    "entry/folder/list",
    async (_arg, thunkApi) => {
        const entry = selectEntry(thunkApi.getState());

        const response = await Ajax.get(Backend.Entry.Folder.List, {
            search: entry.filter,
            auth: true,
        });

        if (response.ok === false) {
            return thunkApi.rejectWithValue(response.error);
        }

        const result = entryFoldersSchema.safeParse(response.result);

        if (result.success === false) {
            return thunkApi.rejectWithValue(result.error);
        }

        return {
            ...entry,
            status: "succeeded",
            items: result.data,
        };
    },
    {
        condition(_arg, { getState }) {
            const entry = selectEntry(getState());
            if (entry.status === "loading") return false;
        },
    },
);

export const detailFolder = createAsyncThunk<
    EntryState,
    { id: string },
    {
        dispatch: AppDispatch;
        state: RootState;
    }
>(
    "entry/folder/detail",
    async ({ id }, thunkApi) => {
        const entry = selectEntry(thunkApi.getState());

        const response = await Ajax.get(Backend.Entry.Folder.Details, {
            search: {
                id,
            },
            auth: true,
        });

        if (response.ok === false) {
            return thunkApi.rejectWithValue(response.error);
        }
        console.log(response.result);
        const result = entryItemsSchema.safeParse(response.result);

        if (result.success === false) {
            return thunkApi.rejectWithValue(result.error);
        }

        const items = entry.items.map((item) => {
            if (item.id === id) {
                return {
                    ...item,
                    items: result.data,
                };
            }
            return item;
        });

        return {
            ...entry,
            status: "succeeded",
            items,
        };
    },
    {
        condition(_arg, { getState }) {
            const entry = selectEntry(getState());
            if (entry.status === "loading") return false;
        },
    },
);

const entrySlice = createSlice({
    name: "entry",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setFilter: (
            state,
            action: PayloadAction<{
                type: string;
                value: string | undefined;
            }>,
        ) => {
            switch (action.payload.type) {
                case "name":
                case "username":
                case "templateName":
                case "tags":
                    state.filter[action.payload.type] = action.payload.value;
                    break;
                case "publicShared":
                case "shared":
                case "includeOwned":
                case "directUser":
                    if (action.payload.value === "true" || action.payload.value === "false") {
                        state.filter[action.payload.type] = action.payload.value;
                        break;
                    }
                    state.filter[action.payload.type] = undefined;
                    break;
            }
        },
        setHideFilters: (state) => {
            state.hideFilters = !state.hideFilters;
        },
        setHideList: (state) => {
            state.hideList = !state.hideList;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(listFolder.pending, (state) => {
                state.status = "loading";
            })
            .addCase(listFolder.fulfilled, (state, action) => {
                if (action.payload.status !== "succeeded") return;
                state.status = "succeeded";
                state.items = action.payload.items;
            })
            .addCase(listFolder.rejected, (state) => {
                state.status = "failed";
            })
            .addCase(detailFolder.pending, (state) => {
                state.status = "loading";
            })
            .addCase(detailFolder.fulfilled, (state, action) => {
                if (action.payload.status !== "succeeded") return;
                state.status = "succeeded";
                state.items = action.payload.items;
            })
            .addCase(detailFolder.rejected, (state) => {
                state.status = "failed";
            });
    },
});

export const { setFilter, setHideFilters, setHideList } = entrySlice.actions;
export const selectEntry = (state: RootState) => state.entry;
export default entrySlice.reducer;
