import { lazy } from "react";

export default {
    AddBlackCircularButton: lazy(() => import("./AddBlackCircularButton")),
    AddingBlackSquareButtonInterfaceSymbol: lazy(
        () => import("./AddingBlackSquareButtonInterfaceSymbol"),
    ),
    AdditionSign: lazy(() => import("./AdditionSign")),
    AirplaneSilhouette: lazy(() => import("./AirplaneSilhouette")),
    AlarmClock: lazy(() => import("./AlarmClock")),
    ArrowAnglePointingToRight: lazy(() => import("./ArrowAnglePointingToRight")),
    ArrowsCoupleCounterclockwiseRotatingSymbol: lazy(
        () => import("./ArrowsCoupleCounterclockwiseRotatingSymbol"),
    ),
    AscendantArrow: lazy(() => import("./AscendantArrow")),
    AttachPaperclipSymbol: lazy(() => import("./AttachPaperclipSymbol")),
    AuricularsSolidToolSymbol: lazy(() => import("./AuricularsSolidToolSymbol")),
    BackArrowSolidSquareButton: lazy(() => import("./BackArrowSolidSquareButton")),
    BackBlackSquareInterfaceButtonSymbol: lazy(
        () => import("./BackBlackSquareInterfaceButtonSymbol"),
    ),
    BagRoundedRectangularBlackToolShape: lazy(
        () => import("./BagRoundedRectangularBlackToolShape"),
    ),
    BellBlackSolidMusicalInstrument: lazy(() => import("./BellBlackSolidMusicalInstrument")),
    BellSilhouetteBlackShapeInterfaceSymbolOfAlarm: lazy(
        () => import("./BellSilhouetteBlackShapeInterfaceSymbolOfAlarm"),
    ),
    BlackCellphoneBack: lazy(() => import("./BlackCellphoneBack")),
    BlackCircularGraphic: lazy(() => import("./BlackCircularGraphic")),
    BlackHalfSun: lazy(() => import("./BlackHalfSun")),
    BlackInkDropShape: lazy(() => import("./BlackInkDropShape")),
    BlackMapFoldedPaperSymbol: lazy(() => import("./BlackMapFoldedPaperSymbol")),
    BlackOvalSpeechBubble: lazy(() => import("./BlackOvalSpeechBubble")),
    BlackPlaceholderForMaps: lazy(() => import("./BlackPlaceholderForMaps")),
    BlackSilhouetteShapeOfAnObjectLikeASpoon: lazy(
        () => import("./BlackSilhouetteShapeOfAnObjectLikeASpoon"),
    ),
    BlackSquareButtonWithAnArrowPointingOutToUpperRight: lazy(
        () => import("./BlackSquareButtonWithAnArrowPointingOutToUpperRight"),
    ),
    BlackTagInterfaceSymbolInVerticalPosition: lazy(
        () => import("./BlackTagInterfaceSymbolInVerticalPosition"),
    ),
    BlackWindsSocketToolSymbol: lazy(() => import("./BlackWindsSocketToolSymbol")),
    BookBlackOpenedSymbol: lazy(() => import("./BookBlackOpenedSymbol")),
    BookmarkBigBlackSolidRoundedInterfaceSymbol: lazy(
        () => import("./BookmarkBigBlackSolidRoundedInterfaceSymbol"),
    ),
    BottleBlackContainer: lazy(() => import("./BottleBlackContainer")),
    BrokenBlackTicketSymbol: lazy(() => import("./BrokenBlackTicketSymbol")),
    Buttons: lazy(() => import("./Buttons")),
    CalendarEventsSymbol: lazy(() => import("./CalendarEventsSymbol")),
    CallBlackAuricularInterfaceSymbol: lazy(() => import("./CallBlackAuricularInterfaceSymbol")),
    CenterText: lazy(() => import("./CenterText")),
    ChatBlackRectangularRoundedSpeechBalloonInterfaceSymbol: lazy(
        () => import("./ChatBlackRectangularRoundedSpeechBalloonInterfaceSymbol"),
    ),
    ChatOvalBlackBalloonsCouple: lazy(() => import("./ChatOvalBlackBalloonsCouple")),
    ChatOvalBlackInterfaceSymbolWithTextLines: lazy(
        () => import("./ChatOvalBlackInterfaceSymbolWithTextLines"),
    ),
    ClipboardBlackSquareInterfaceSymbol: lazy(
        () => import("./ClipboardBlackSquareInterfaceSymbol"),
    ),
    ClockBlackCircularTool: lazy(() => import("./ClockBlackCircularTool")),
    CloseArrowShapeButtonInterfaceSymbol: lazy(
        () => import("./CloseArrowShapeButtonInterfaceSymbol"),
    ),
    CloudBlackShape: lazy(() => import("./CloudBlackShape")),
    CloudBlackStormSymbolOfWeatherWithHailDotsFalling: lazy(
        () => import("./CloudBlackStormSymbolOfWeatherWithHailDotsFalling"),
    ),
    CompassBlackCircularOrientationTool: lazy(
        () => import("./CompassBlackCircularOrientationTool"),
    ),
    ConfigurationGrossBlackCogwheelSymbolOfInterface: lazy(
        () => import("./ConfigurationGrossBlackCogwheelSymbolOfInterface"),
    ),
    CopyBlackSquareSymbol: lazy(() => import("./CopyBlackSquareSymbol")),
    Copy: lazy(() => import("./Copy")),
    CounterclockwiseCircularArrow: lazy(() => import("./CounterclockwiseCircularArrow")),
    CroppingDesignInterfaceSymbolOfStraightLines: lazy(
        () => import("./CroppingDesignInterfaceSymbolOfStraightLines"),
    ),
    CrossBlackCircularButton: lazy(() => import("./CrossBlackCircularButton")),
    CrossSquareBlackButton: lazy(() => import("./CrossSquareBlackButton")),
    Cross: lazy(() => import("./Cross")),
    CupTrophySilhouette: lazy(() => import("./CupTrophySilhouette")),
    DiagonalArrowEnteringInBlackSquareButton: lazy(
        () => import("./DiagonalArrowEnteringInBlackSquareButton"),
    ),
    DoubleHorizontalArrow: lazy(() => import("./DoubleHorizontalArrow")),
    DoubleLeftArrowsSymbol: lazy(() => import("./DoubleLeftArrowsSymbol")),
    DoubleVerticalArrow: lazy(() => import("./DoubleVerticalArrow")),
    DownArrowBlackCircularButton1: lazy(() => import("./DownArrowBlackCircularButton1")),
    DownArrowBlackCircularButton: lazy(() => import("./DownArrowBlackCircularButton")),
    DownArrowBlackSquareButton1: lazy(() => import("./DownArrowBlackSquareButton1")),
    DownArrowBlackSquareButton: lazy(() => import("./DownArrowBlackSquareButton")),
    DownArrowSymbolInBlackSquareButton: lazy(() => import("./DownArrowSymbolInBlackSquareButton")),
    DownArrowSymbol: lazy(() => import("./DownArrowSymbol")),
    DownArrow: lazy(() => import("./DownArrow")),
    DownloadBlackCloudInterfaceSymbolWithDownArrowInside: lazy(
        () => import("./DownloadBlackCloudInterfaceSymbolWithDownArrowInside"),
    ),
    DownloadBlackSquareInterfaceButtonSymbol: lazy(
        () => import("./DownloadBlackSquareInterfaceButtonSymbol"),
    ),
    DownloadInterfaceSymbolOfDownArrowOnAndInABlackSquare: lazy(
        () => import("./DownloadInterfaceSymbolOfDownArrowOnAndInABlackSquare"),
    ),
    Download: lazy(() => import("./Download")),
    EmailBlackEnvelopeFrontInterfaceSymbol: lazy(
        () => import("./EmailBlackEnvelopeFrontInterfaceSymbol"),
    ),
    EmailBlackEnvelopeSymbol: lazy(() => import("./EmailBlackEnvelopeSymbol")),
    EmailBlackOpenedBackEnvelopeInterfaceSymbol: lazy(
        () => import("./EmailBlackOpenedBackEnvelopeInterfaceSymbol"),
    ),
    EqualizerBlackSquareButton: lazy(() => import("./EqualizerBlackSquareButton")),
    Equalizer: lazy(() => import("./Equalizer")),
    EventCalendarSymbol: lazy(() => import("./EventCalendarSymbol")),
    ExpandButtonBlackSquareInterfaceSymbol: lazy(
        () => import("./ExpandButtonBlackSquareInterfaceSymbol"),
    ),
    ExpandTwoDiagonalArrowsSymbol: lazy(() => import("./ExpandTwoDiagonalArrowsSymbol")),
    FastForwardDoubleBlackArrowsMultimediaSymbol: lazy(
        () => import("./FastForwardDoubleBlackArrowsMultimediaSymbol"),
    ),
    FastForwardDoubleRightArrowsSymbol: lazy(() => import("./FastForwardDoubleRightArrowsSymbol")),
    FileBlackRoundedSymbol1: lazy(() => import("./FileBlackRoundedSymbol1")),
    FileBlackRoundedSymbol: lazy(() => import("./FileBlackRoundedSymbol")),
    FilesCopyInterfaceSymbol: lazy(() => import("./FilesCopyInterfaceSymbol")),
    FilmStripPieceOfTwoPhotograms: lazy(() => import("./FilmStripPieceOfTwoPhotograms")),
    FlagBlackCuttedShape: lazy(() => import("./FlagBlackCuttedShape")),
    FoggyDay: lazy(() => import("./FoggyDay")),
    FoggyFullMoonNight: lazy(() => import("./FoggyFullMoonNight")),
    FoggyNight: lazy(() => import("./FoggyNight")),
    FolderBlackInterfaceSymbol: lazy(() => import("./FolderBlackInterfaceSymbol")),
    ForkBlackSilhouetteOfKitchenEatingUtensil: lazy(
        () => import("./ForkBlackSilhouetteOfKitchenEatingUtensil"),
    ),
    FourBlackButtonsKeyboardOfRoundedSquares: lazy(
        () => import("./FourBlackButtonsKeyboardOfRoundedSquares"),
    ),
    Game: lazy(() => import("./Game")),
    GamesMachine: lazy(() => import("./GamesMachine")),
    Giftbox: lazy(() => import("./Giftbox")),
    GlassOfCocktailSilhouette: lazy(() => import("./GlassOfCocktailSilhouette")),
    Globe: lazy(() => import("./Globe")),
    GraphicOfBarsOnScreen: lazy(() => import("./GraphicOfBarsOnScreen")),
    HotOrBurnInterfaceSymbol: lazy(() => import("./HotOrBurnInterfaceSymbol")),
    ImageSquareInterfaceButton: lazy(() => import("./ImageSquareInterfaceButton")),
    JustifyText: lazy(() => import("./JustifyText")),
    KeyboardOfNineCircleForDigitalDevices: lazy(
        () => import("./KeyboardOfNineCircleForDigitalDevices"),
    ),
    KnifeShape: lazy(() => import("./KnifeShape")),
    LeftAlignmentInterfaceSymbol: lazy(() => import("./LeftAlignmentInterfaceSymbol")),
    LeftArrowAndBlackSquareSymbol: lazy(() => import("./LeftArrowAndBlackSquareSymbol")),
    LeftArrowAngleBigGrossSymbol: lazy(() => import("./LeftArrowAngleBigGrossSymbol")),
    LeftArrowBlackButtonSquare: lazy(() => import("./LeftArrowBlackButtonSquare")),
    LeftArrowBlackCircularButton: lazy(() => import("./LeftArrowBlackCircularButton")),
    LeftArrowCurvedBlackSymbol: lazy(() => import("./LeftArrowCurvedBlackSymbol")),
    LeftArrowInCircularButtonBlackSymbol: lazy(
        () => import("./LeftArrowInCircularButtonBlackSymbol"),
    ),
    LeftBlackArrowSymbol: lazy(() => import("./LeftBlackArrowSymbol")),
    LikeSolidHeartBlackSymbolForInterface: lazy(
        () => import("./LikeSolidHeartBlackSymbolForInterface"),
    ),
    Link: lazy(() => import("./Link")),
    ListInterfaceSymbol: lazy(() => import("./ListInterfaceSymbol")),
    ListSymbolOfThreeItemsWithDots: lazy(() => import("./ListSymbolOfThreeItemsWithDots")),
    LockedCircularBlackPadlockInterfaceSecuritySymbol: lazy(
        () => import("./LockedCircularBlackPadlockInterfaceSecuritySymbol"),
    ),
    LoginSymbolOfAnArrowEnteringToABlackSquare: lazy(
        () => import("./LoginSymbolOfAnArrowEnteringToABlackSquare"),
    ),
    MegaphoneBlackAmplificationAudioToolSymbol: lazy(
        () => import("./MegaphoneBlackAmplificationAudioToolSymbol"),
    ),
    MenuBlackRoundedSquareInterfaceButton: lazy(
        () => import("./MenuBlackRoundedSquareInterfaceButton"),
    ),
    MenuButton: lazy(() => import("./MenuButton")),
    MenuGrossInterfaceSymbol: lazy(() => import("./MenuGrossInterfaceSymbol")),
    MinusBigSymbol: lazy(() => import("./MinusBigSymbol")),
    MinusCircularBlackButton: lazy(() => import("./MinusCircularBlackButton")),
    MinusSolidBlackSquareButton: lazy(() => import("./MinusSolidBlackSquareButton")),
    MobileDeviceBlackSymbol: lazy(() => import("./MobileDeviceBlackSymbol")),
    MonitorBlackTool: lazy(() => import("./MonitorBlackTool")),
    MoonPhaseBlackCrescentShape: lazy(() => import("./MoonPhaseBlackCrescentShape")),
    Move: lazy(() => import("./Move")),
    MovieSymbolOfVideoCamera: lazy(() => import("./MovieSymbolOfVideoCamera")),
    MusicAmplifier: lazy(() => import("./MusicAmplifier")),
    MusicNoteSymbol: lazy(() => import("./MusicNoteSymbol")),
    MusicSolidRectangularRoundedButton: lazy(() => import("./MusicSolidRectangularRoundedButton")),
    MusicSquareFrontalSpeakerAmplifyingToolSymbol: lazy(
        () => import("./MusicSquareFrontalSpeakerAmplifyingToolSymbol"),
    ),
    MusicThemeInfoInterfaceSymbolOfMusicalNoteWithTextLines: lazy(
        () => import("./MusicThemeInfoInterfaceSymbolOfMusicalNoteWithTextLines"),
    ),
    MusicalNoteBlackSymbol: lazy(() => import("./MusicalNoteBlackSymbol")),
    MusicalNote: lazy(() => import("./MusicalNote")),
    MuteMicrophoneInterfaceSymbol: lazy(() => import("./MuteMicrophoneInterfaceSymbol")),
    MuteSpeakerSymbolOfInterfaceWithACross: lazy(
        () => import("./MuteSpeakerSymbolOfInterfaceWithACross"),
    ),
    NewEmailBlackBackEnvelopeSymbolOfInterface: lazy(
        () => import("./NewEmailBlackBackEnvelopeSymbolOfInterface"),
    ),
    NotebookBlackToolSymbol: lazy(() => import("./NotebookBlackToolSymbol")),
    OvalBlackSpeechBalloonWithThreeDotsInside: lazy(
        () => import("./OvalBlackSpeechBalloonWithThreeDotsInside"),
    ),
    OvalBlackSpeechBalloon: lazy(() => import("./OvalBlackSpeechBalloon")),
    Paintbrush: lazy(() => import("./Paintbrush")),
    PaperPlaneBlackFoldedShapeOfTriangularArrow: lazy(
        () => import("./PaperPlaneBlackFoldedShapeOfTriangularArrow"),
    ),
    PaperclipInVerticalPosition: lazy(() => import("./PaperclipInVerticalPosition")),
    PauseMultimediaBigGrossSymbolLines: lazy(() => import("./PauseMultimediaBigGrossSymbolLines")),
    PencilBigBlackWritingTool: lazy(() => import("./PencilBigBlackWritingTool")),
    PersonBlackUserShape: lazy(() => import("./PersonBlackUserShape")),
    PersonInfo: lazy(() => import("./PersonInfo")),
    PhotoCameraBlackTool: lazy(() => import("./PhotoCameraBlackTool")),
    PinBlackSolidSilhouetteOfTool: lazy(() => import("./PinBlackSolidSilhouetteOfTool")),
    PlayBlackTriangleInterfaceSymbolForMultimedia: lazy(
        () => import("./PlayBlackTriangleInterfaceSymbolForMultimedia"),
    ),
    PlusSignOnZoomMagnifier: lazy(() => import("./PlusSignOnZoomMagnifier")),
    PortfolioBlackSymbol: lazy(() => import("./PortfolioBlackSymbol")),
    PrintingButtonInterfaceSymbol: lazy(() => import("./PrintingButtonInterfaceSymbol")),
    PrizeBadge: lazy(() => import("./PrizeBadge")),
    RadioBlackToolSymbol: lazy(() => import("./RadioBlackToolSymbol")),
    RewindMultimediaButtonSymbolOfTwoBlackArrows: lazy(
        () => import("./RewindMultimediaButtonSymbolOfTwoBlackArrows"),
    ),
    RightArrowAngleBlackCircularInterfaceSymbol: lazy(
        () => import("./RightArrowAngleBlackCircularInterfaceSymbol"),
    ),
    RightArrowBlackButton: lazy(() => import("./RightArrowBlackButton")),
    RightArrowBlackSquareButton: lazy(() => import("./RightArrowBlackSquareButton")),
    RightArrowInBlackCircularButton: lazy(() => import("./RightArrowInBlackCircularButton")),
    RightArrowSolidSquareButton: lazy(() => import("./RightArrowSolidSquareButton")),
    RightArrowSymbol: lazy(() => import("./RightArrowSymbol")),
    RightBlackArrowSignal: lazy(() => import("./RightBlackArrowSignal")),
    RingBellOfHotelReception: lazy(() => import("./RingBellOfHotelReception")),
    RoundedCornersInterfaceSquareSymbol: lazy(
        () => import("./RoundedCornersInterfaceSquareSymbol"),
    ),
    SandClockSilhouette: lazy(() => import("./SandClockSilhouette")),
    SaveBlackDisketteInterfaceSymbol: lazy(() => import("./SaveBlackDisketteInterfaceSymbol")),
    SearchMagnifierBlackShape: lazy(() => import("./SearchMagnifierBlackShape")),
    ShareBlackSolidSocialSymbol: lazy(() => import("./ShareBlackSolidSocialSymbol")),
    ShoppingBasketCommercialTool: lazy(() => import("./ShoppingBasketCommercialTool")),
    ShoppingCartBlackSilhouette: lazy(() => import("./ShoppingCartBlackSilhouette")),
    ShoppingCartSilhouette: lazy(() => import("./ShoppingCartSilhouette")),
    ShuffleTwoArrowsSymbol: lazy(() => import("./ShuffleTwoArrowsSymbol")),
    SolidAscendantArrowSymbol: lazy(() => import("./SolidAscendantArrowSymbol")),
    SolidBlackSunSymbol: lazy(() => import("./SolidBlackSunSymbol")),
    SortAscendingInterfaceSymbol: lazy(() => import("./SortAscendingInterfaceSymbol")),
    SortDownInterfaceSymbol: lazy(() => import("./SortDownInterfaceSymbol")),
    SpeakerAudioTool: lazy(() => import("./SpeakerAudioTool")),
    SpeakerBlackAudioInterfaceSymbol: lazy(() => import("./SpeakerBlackAudioInterfaceSymbol")),
    Speaker: lazy(() => import("./Speaker")),
    SquareBlackGeometricShape: lazy(() => import("./SquareBlackGeometricShape")),
    SquareShapeWithDotsOnCorners: lazy(() => import("./SquareShapeWithDotsOnCorners")),
    SquaresStack: lazy(() => import("./SquaresStack")),
    StarBlackFivepointedShapeSymbol: lazy(() => import("./StarBlackFivepointedShapeSymbol")),
    StoreCommercialSymbol: lazy(() => import("./StoreCommercialSymbol")),
    StormBlackCloudSymbol: lazy(() => import("./StormBlackCloudSymbol")),
    StormBlackCloudWithALightningBoltShapeInside: lazy(
        () => import("./StormBlackCloudWithALightningBoltShapeInside"),
    ),
    SwitchBlackSolidSymbol: lazy(() => import("./SwitchBlackSolidSymbol")),
    SwitchBlackToolSymbol: lazy(() => import("./SwitchBlackToolSymbol")),
    TagBlackSymbol: lazy(() => import("./TagBlackSymbol")),
    TargetBlackCircularSymbol: lazy(() => import("./TargetBlackCircularSymbol")),
    ThreeBarsGraphicInterfaceSymbol: lazy(() => import("./ThreeBarsGraphicInterfaceSymbol")),
    TimerBlackToolSymbol: lazy(() => import("./TimerBlackToolSymbol")),
    TrashCanBlackSymbol: lazy(() => import("./TrashCanBlackSymbol")),
    Trash: lazy(() => import("./Trash")),
    TravelBagOfVerticalBlackDesign: lazy(() => import("./TravelBagOfVerticalBlackDesign")),
    TvMonitor: lazy(() => import("./TvMonitor")),
    TwoArrowsInBlackSquareButton: lazy(() => import("./TwoArrowsInBlackSquareButton")),
    TwoArrowsTrianglesPointingToSidesWithASlashLineInTheMiddle: lazy(
        () => import("./TwoArrowsTrianglesPointingToSidesWithASlashLineInTheMiddle"),
    ),
    TwoArrows: lazy(() => import("./TwoArrows")),
    TwoBlackDropsOfDifferentSizes: lazy(() => import("./TwoBlackDropsOfDifferentSizes")),
    TwoClockwiseCircularRotatingArrowsCircle: lazy(
        () => import("./TwoClockwiseCircularRotatingArrowsCircle"),
    ),
    TwoOppositeDiagonalArrowsInBlackSquare: lazy(
        () => import("./TwoOppositeDiagonalArrowsInBlackSquare"),
    ),
    UnlockedPadlock: lazy(() => import("./UnlockedPadlock")),
    UpArrowBlackSquareButton1: lazy(() => import("./UpArrowBlackSquareButton1")),
    UpArrowBlackSquareButtonInterfaceSymbol: lazy(
        () => import("./UpArrowBlackSquareButtonInterfaceSymbol"),
    ),
    UpArrowBlackSquareButton: lazy(() => import("./UpArrowBlackSquareButton")),
    UpArrowBlackTriangleSymbol: lazy(() => import("./UpArrowBlackTriangleSymbol")),
    UpArrowButton: lazy(() => import("./UpArrowButton")),
    UpArrowEnteringInBlackSquare: lazy(() => import("./UpArrowEnteringInBlackSquare")),
    UpArrowSolidBlackSquareButton: lazy(() => import("./UpArrowSolidBlackSquareButton")),
    UpArrowSolidCircularButton: lazy(() => import("./UpArrowSolidCircularButton")),
    UploadToInternetCloud: lazy(() => import("./UploadToInternetCloud")),
    UploadTrayWithUpArrowInterfaceSymbol: lazy(
        () => import("./UploadTrayWithUpArrowInterfaceSymbol"),
    ),
    VerificationCheckmarkSymbol: lazy(() => import("./VerificationCheckmarkSymbol")),
    VerifyBlackSquareInterfaceButtonSymbol: lazy(
        () => import("./VerifyBlackSquareInterfaceButtonSymbol"),
    ),
    VerifyCircularBlackButtonSymbol: lazy(() => import("./VerifyCircularBlackButtonSymbol")),
    VoiceAmplificationOrRecordingInterfaceSymbolOfAMicrophone: lazy(
        () => import("./VoiceAmplificationOrRecordingInterfaceSymbolOfAMicrophone"),
    ),
    VoiceInterfaceSymbolOfMicrophoneSilhouette: lazy(
        () => import("./VoiceInterfaceSymbolOfMicrophoneSilhouette"),
    ),
    WalletBlackSymbol: lazy(() => import("./WalletBlackSymbol")),
    WeeklyCalendarBlackEventInterfaceSymbol: lazy(
        () => import("./WeeklyCalendarBlackEventInterfaceSymbol"),
    ),
    WindowBlackRoundedSquareInterfaceSymbol: lazy(
        () => import("./WindowBlackRoundedSquareInterfaceSymbol"),
    ),
    WindsWeatherSymbol: lazy(() => import("./WindsWeatherSymbol")),
    WrenchBlackSilhouette: lazy(() => import("./WrenchBlackSilhouette")),
    WritingToolsSymbolOfInterfaceWithBlackSquarePaperNoteAndAPencil: lazy(
        () => import("./WritingToolsSymbolOfInterfaceWithBlackSquarePaperNoteAndAPencil"),
    ),
    ZoomMagnifierWithMinusSymbol: lazy(() => import("./ZoomMagnifierWithMinusSymbol")),
};
